### ISSUE TITLE
Any convenient way to use cpanfile?

### ISSUE THREAD

**Issue by ClayShentrup** [oetiker/sourcey-buildpack#10]
Hi,

I'd love to just use our cpanfile instead of having to duplicate it in a long series of `buildPerlModule` calls. Should I just modify this and put it in SourceyBuild.sh?

https://github.com/oetiker/sourcey-buildpack/blob/08ebffbb27283e5dfa9af26bfa43b3a9e51a6b8e/lib/buildPerlModule.func

Thanks,
Clay

**Comment by oetiker** [comment]
sure, PRs are most welcome. you could add a new function buildPerlModuleFromCpanfile or some such.

**Comment by ClayShentrup** [comment]
Makes sense. Thanks.
