### ISSUE TITLE
Can module builds be verbose?

### ISSUE THREAD

**Issue by shreeniwas-sapre** [oetiker/sourcey-buildpack#5]
If SOURCEY_VERBOSE is enabled, right now the verbosity does not propagate to the perl module builds (buildPerlModule). Such a propagation would be useful to debug failing module builds

**Comment by shreeniwas-sapre** [comment]
Noticed that '-v' can be easily passed to buildPerlModule.

**Comment by oetiker** [comment]
you could create a PR to have -v added when SOURCEY_VERBOSE is set ... not sure if all perl modules react to -v
